#ifndef LUNAR_H
#define LUNAR_H

//////////////////////////////////
//
//			INCLUDES
//
//////////////////////////////////

#include <stddef.h>
#include <stdint.h>

//////////////////////////////////
//
//			DEFINES
//
//////////////////////////////////

#define GET_VALUE_FIELD(value) ( ((value << 2) & 0xFF ) >> 5 & 0xF)

#define INVALID_REGISTER NULL

//////////////////////////////////
//
//			TYPEDEFS	
//
//////////////////////////////////

typedef struct register_t	register_t;
typedef struct opcodes_t	opcodes_t;
typedef struct mnemonic_t	mnemonic_t;
typedef struct rex_prfx_t	rex_prfx_t;
typedef struct mod_rm_t		mod_rm_t;
typedef struct sib_t    	sib_t;
typedef struct inst_t 		inst_t;
typedef struct fmt_t  		fmt_t;
typedef enum   mnemo_idx_t 	mnemo_idx_t;
typedef enum   arch_mode_t	arch_mode_t;

/////////////////////////////////
//
//		MNEMONIC TABLE
//
/////////////////////////////////

struct mnemonic_t
{
	char 	*str;
	size_t	len;
};

/////////////////////////////////
//
//	 	REGISTER TABLES
//
/////////////////////////////////

struct register_t
{
	char	*r8;
	char	*r16;
	char	*r32;
	char	*r64;
	char	*mm;
	char	*xmm;
	char	*sreg;
	char	*cr;
	char	*dr;
};

/////////////////////////////////
//
//		OPCODES TABLES
//
/////////////////////////////////


struct opcodes_t
{
	mnemonic_t	*mnemonic[4];
	uint8_t		len;
	uint8_t		p_rex;
	uint8_t		p_rep;
	uint8_t		p_lock;
	uint8_t		p_seg;
	uint8_t		p_66;
	uint8_t		p_67;
	uint8_t		p_twobyte;
	uint8_t		po;
	uint8_t		so;
	uint8_t		o;
	uint8_t		x;
	uint8_t		op1;
	uint8_t		op2;
	uint8_t		op3;
	uint8_t		op4;
};

//////////////////////////////////
//
//			ENUM
//
//////////////////////////////////


enum arch_mode_t
{
	MODE_X86,
	MODE_X64
};

enum mnemo_idx_t
{
			MNEMO_ADD,
			MNEMO_PUSH,
			MNEMO_POP,
			MNEMO_OR,
			MNEMO_ADC,
			MNEMO_SBB,
			MNEMO_AND,
			MNEMO_DAA,
			MNEMO_SUB,
			MNEMO_DAS,
			MNEMO_XOR,
			MNEMO_AAA,
			MNEMO_CMP,
			MNEMO_AAS,
			MNEMO_INC,
			MNEMO_DEC,
			MNEMO_PUSHA,
			MNEMO_PUSHAD,
			MNEMO_POPA,
			MNEMO_POPAD,
			MNEMO_BOUND,
			MNEMO_ARPL,
			MNEMO_IMUL,
			MNEMO_INS,
			MNEMO_INSB,
			MNEMO_INSW,
			MNEMO_INSD,
			MNEMO_OUTS,
			MNEMO_OUTSB,
			MNEMO_OUTSW,
			MNEMO_OUTSD,
			MNEMO_JO,
			MNEMO_JNO,
			MNEMO_JB,
			MNEMO_JNAE,
			MNEMO_JC,
			MNEMO_JNB,
			MNEMO_JAE,
			MNEMO_JNC,
			MNEMO_JZ,
			MNEMO_JE,
			MNEMO_JNZ,
			MNEMO_JNE,
			MNEMO_JBE,
			MNEMO_JNA,
			MNEMO_JNBE,
			MNEMO_JA,
			MNEMO_JS,
			MNEMO_JNS,
			MNEMO_JP,
			MNEMO_JPE,
			MNEMO_JNP,
			MNEMO_JPO,
			MNEMO_JL,
			MNEMO_JNGE,
			MNEMO_JNL,
			MNEMO_JGE,
			MNEMO_JLE,
			MNEMO_JNG,
			MNEMO_JNLE,
			MNEMO_JG,
			MNEMO_TEST,
			MNEMO_XCHG,
			MNEMO_MOV,
			MNEMO_LEA,
			MNEMO_NOP,
			MNEMO_PAUSE,
			MNEMO_CBW,
			MNEMO_CWDE,
			MNEMO_CWD,
			MNEMO_CDQ,
			MNEMO_CALLF,
			MNEMO_FWAIT,
			MNEMO_WAIT,
			MNEMO_PUSHF,
			MNEMO_PUSHFD,
			MNEMO_POPF,
			MNEMO_POPFD,
			MNEMO_SAHF,
			MNEMO_LAHF,
			MNEMO_MOVS,
			MNEMO_MOVSB,
			MNEMO_MOVSW,
			MNEMO_MOVSD,
			MNEMO_CMPS,
			MNEMO_CMPSB,
			MNEMO_CMPSW,
			MNEMO_CMPSD,
			MNEMO_STOS,
			MNEMO_STOSB,
			MNEMO_STOSW,
			MNEMO_STOSD,
			MNEMO_LODS,
			MNEMO_LODSB,
			MNEMO_LODSW,
			MNEMO_LODSD,
			MNEMO_SCAS,
			MNEMO_SCASB,
			MNEMO_SCASW,
			MNEMO_SCASD,
			MNEMO_ROL,
			MNEMO_ROR,
			MNEMO_RCL,
			MNEMO_RCR,
			MNEMO_SHL,
			MNEMO_SAL,
			MNEMO_SHR,
			MNEMO_SAR,
			MNEMO_RETN,
			MNEMO_LES,
			MNEMO_LDS,
			MNEMO_ENTER,
			MNEMO_LEAVE,
			MNEMO_RETF,
			MNEMO_INT,
			MNEMO_INTO,
			MNEMO_IRET,
			MNEMO_IRETD,
			MNEMO_AAM,
			MNEMO_AMX,
			MNEMO_AAD,
			MNEMO_ADX,
			MNEMO_SALC,
			MNEMO_SETALC,
			MNEMO_XLAT,
			MNEMO_XLATB,
			MNEMO_FADD,
			MNEMO_FMUL,
			MNEMO_FCOM,
			MNEMO_FCOMP,
			MNEMO_FSUB,
			MNEMO_FSUBR,
			MNEMO_FDIV,
			MNEMO_FDIVR,
			MNEMO_FLD,
			MNEMO_FXCH,
			MNEMO_FST,
			MNEMO_FNOP,
			MNEMO_FSTP,
			MNEMO_FSTP1,
			MNEMO_FLDENV,
			MNEMO_FCHS,
			MNEMO_FABS,
			MNEMO_FTST,
			MNEMO_FXAM,
			MNEMO_FLDCW,
			MNEMO_FLD1,
			MNEMO_FLD2T,
			MNEMO_FLD2E,
			MNEMO_FLDPI,
			MNEMO_FLDG2,
			MNEMO_FLDN2,
			MNEMO_FLDZ,
			MNEMO_FNSTENV,
			MNEMO_FSTENV,
			MNEMO_F2XM1,
			MNEMO_FYL2X,
			MNEMO_FPTAN,
			MNEMO_FPATAN,
			MNEMO_FXTRACT,
			MNEMO_FPREM1,
			MNEMO_FDECSTP,
			MNEMO_FINCSTP,
			MNEMO_FNSTCW,
			MNEMO_FSTCW,
			MNEMO_FPREM,
			MNEMO_FYL2XP1,
			MNEMO_FSQRT,
			MNEMO_FSINCOS,
			MNEMO_FRNDINT,
			MNEMO_FSCALE,
			MNEMO_FSIN,
			MNEMO_FCOS,
			MNEMO_FIADD,
			MNEMO_FCMOVB,
			MNEMO_FIMUL,
			MNEMO_FCMOVE,
			MNEMO_FICOM,
			MNEMO_FCMOVBE,
			MNEMO_FICOMP,
			MNEMO_FCMOVU,
			MNEMO_FISUB,
			MNEMO_FISUBR,
			MNEMO_FUCOMPP,
			MNEMO_FIDIV,
			MNEMO_FIDIVR,
			MNEMO_FILD,
			NEMO_FCMOVNB,
			MNEMO_FISTTP,
			MNEMO_FCMOVNE,
			MNEMO_FIST,
			MNEMO_FCMOVNBE,
			MNEMO_FISTP,
			MNEMO_FCMOVNU,
			MNEMO_FNENI,
			MNEMO_FNDISI,
			MNEMO_FNCLEX,
			MNEMO_FCLEX,
			MNEMO_FNINIT,
			MNEMO_FINIT,
			MNEMO_FNSETPM,
			MNEMO_FUCOMI,
			MNEMO_FCOMI,
			MNEMO_FCOM2,
			MNEMO_FCOMP3,
			MNEMO_FFREE,
			MNEMO_FXCH4,
			MNEMO_FRSTOR,
			MNEMO_FUCOM,
			MNEMO_FUCOMP,
			MNEMO_FNSAVE,
			MNEMO_FSAVE,
			MNEMO_FNSTW,
			MNEMO_FSTSW,
			MNEMO_FADDP,
			MNEMO_FMULP,
			MNEMO_FCOMP5,
			MNEMO_FCOMPP,
			MNEMO_FSUBRP,
			MNEMO_FSUBP,
			MNEMO_FDIVRP,
			MNEMO_FDIVP,
			MNEMO_FFREEP,
			MNEMO_FXCH7,
			MNEMO_FSTP8,
			MNEMO_FSTP9,
			MNEMO_FBLD,
			MNEMO_FNSTSW,
			MNEMO_FUCOMIP,
			MNEMO_FBSTP,
			MNEMO_FCOMIP,
			MNEMO_LOOPNZ,
			MNEMO_LOOPNE,
			MNEMO_LOOPZ,
			MNEMO_LOOPE,
			MNEMO_LOOP,
			MNEMO_JCXZ,
			MNEMO_JECXZ,
			MNEMO_IN,
			MNEMO_OUT,
			MNEMO_CALL,
			MNEMO_JMP,
			MNEMO_JMPF,
			MNEMO_INT1,
			MNEMO_ICEBP,
			MNEMO_REPNZ,
			MNEMO_REPNE,
			MNEMO_REP,
			MNEMO_HLT,
			MNEMO_CMC,
			MNEMO_NOT,
			MNEMO_NEG,
			MNEMO_MUL,
			MNEMO_DIV,
			MNEMO_IDIV,
			MNEMO_CLC,
			MNEMO_STC,
			MNEMO_CLI,
			MNEMO_STI,
			MNEMO_CLD,
			MNEMO_STD,
			MNEMO_SLDT,
			MNEMO_STR,
			MNEMO_LLDT,
			MNEMO_LTR,
			MNEMO_VERR,
			MNEMO_VERW,
			MNEMO_SGDT,
			MNEMO_VMCALL,
			MNEMO_VMLAUNCH,
			MNEMO_VMRESUME,
			MNEMO_VMXOFF,
			MNEMO_SIDT,
			MNEMO_MONITOR,
			MNEMO_MWAIT,
			MNEMO_LGDT,
			MNEMO_XGETBV,
			MNEMO_XSETBV,
			MNEMO_LIDT,
			MNEMO_SMSW,
			MNEMO_LMSW,
			MNEMO_INVLPG,
			MNEMO_RDTSCP,
			MNEMO_LAR,
			MNEMO_LSL,
			MNEMO_CLTS,
			MNEMO_INVD,
			MNEMO_WBINVD,
			MNEMO_UD2,
			MNEMO_MOVUPS,
			MNEMO_MOVSS,
			MNEMO_MOVUPD,
			MNEMO_MOVHLPS,
			MNEMO_MOVLPS,
			MNEMO_MOVLPD,
			MNEMO_MOVDDUP,
			MNEMO_MOVSLDUP,
			MNEMO_UNPCKLPS,
			MNEMO_UNPCKLPD,
			MNEMO_UNPCKHPS,
			MNEMO_UNPCKHPD,
			MNEMO_MOVHPS,
			MNEMO_MOVHPD,
			MNEMO_PREFETCHNTA,
			MNEMO_PREFETCHT0,
			MNEMO_PREFETCHT1,
			MNEMO_PREFETCHT2,
			MNEMO_HINT_NOP,
			MNEMO_MOVAPS,
			MNEMO_MOVAPD,
			MNEMO_CVTPI2PS,
			MNEMO_CVTSI2SS,
			MNEMO_CVTPI2PD,
			MNEMO_CVTSI2SD,
			MNEMO_MOVNTPS,
			MNEMO_MOVNTPD,
			MNEMO_CVTTPS2PI,
			MNEMO_CVTTSS2SI,
			MNEMO_CVTTPD2PI,
			MNEMO_CVTTSD2SI,
			MNEMO_UCOMISS,
			MNEMO_UCOMISD,
			MNEMO_WRMSR,
			MNEMO_RDTSC,
			MNEMO_RDMSR,
			MNEMO_RDPMC,
			MNEMO_SYSENTER,
			MNEMO_SYSEXIT,
			MNEMO_GETSEC,
			MNEMO_PSHUFB,
			MNEMO_PHADDW,
			MNEMO_PHADDD,
			MNEMO_PHADDSW,
			MNEMO_PMADDUBSW,
			MNEMO_PHSUBW,
			MNEMO_PHSUBD,
			MNEMO_PSIGNB,
			MNEMO_PSIGNW,
			MNEMO_PSIGND,
			MNEMO_PMULHRSW,
			MNEMO_PBLENDVB,
			MNEMO_BLENDVPS,
			MNEMO_BLENDVPD,
			MNEMO_PTEST,
			MNEMO_PABSB,
			MNEMO_PABSW,
			MNEMO_PABSD,
			MNEMO_PMOVSXBW,
			MNEMO_PMOVSXBD,
			MNEMO_PMOVSXBQ,
			MNEMO_PMOVSXWD,
			MNEMO_PMOVSXWQ,
			MNEMO_PMOVSXDQ,
			MNEMO_PMULDQ,
			MNEMO_PCMPEQQ,
			MNEMO_MOVNTDQA,
			MNEMO_PACKUSDW,
			MNEMO_PMOVZXBW,
			MNEMO_PMOVZXBD,
			MNEMO_PMOVZXBQ,
			MNEMO_PMOVZXWD,
			MNEMO_PMOVZXWQ,
			MNEMO_PMOVZXDQ,
			MNEMO_PCMPGTQ,
			MNEMO_PMINSB,
			MNEMO_PMINSD,
			MNEMO_PMINUW,
			MNEMO_PMINUD,
			MNEMO_PMAXSB,
			MNEMO_PMAXSD,
			MNEMO_PMAXUW,
			MNEMO_PMAXUD,
			MNEMO_PMULLD,
			MNEMO_PHMINPOSUW,
			MNEMO_INVEPT,
			MNEMO_INVVPID,
			MNEMO_MOVBE,
			MNEMO_CRC32,
			MNEMO_ROUNDPS,
			MNEMO_ROUNDPD,
			MNEMO_ROUNDSS,
			MNEMO_ROUNDSD,
			MNEMO_BLENDPS,
			MNEMO_BLENDPD,
			MNEMO_PBLENDW,
			MNEMO_PALIGNR,
			MNEMO_PEXTRB,
			MNEMO_PEXTRW,
			MNEMO_PEXTRD,
			MNEMO_PEXTRQ,
			MNEMO_EXTRACTPS,
			MNEMO_PINSRB,
			MNEMO_INSERTPS,
			MNEMO_PINSRD,
			MNEMO_PINSRQ,
			MNEMO_DPPS,
			MNEMO_DPPD,
			MNEMO_MPSADBW,
			MNEMO_PCMPESTRM,
			MNEMO_PCMPESTRI,
			MNEMO_PCMPISTRM,
			MNEMO_PCMPISTRI,
			MNEMO_CMOVO,
			MNEMO_CMOVNO,
			MNEMO_CMOVB,
			MNEMO_CMOVNAE,
			MNEMO_CMOVC,
			MNEMO_CMOVNB,
			MNEMO_CMOVAE,
			MNEMO_CMOVNC,
			MNEMO_CMOVZ,
			MNEMO_CMOVE,
			MNEMO_CMOVNZ,
			MNEMO_CMOVNE,
			MNEMO_CMOVNBE,
			MNEMO_CMOVA,
			MNEMO_CMOVNA,
			MNEMO_CMOVBE,
			MNEMO_CMOVS,
			MNEMO_CMOVNS,
			MNEMO_CMOVP,
			MNEMO_CMOVPE,
			MNEMO_CMOVNP,
			MNEMO_CMOVPO,
			MNEMO_CMOVL,
			MNEMO_CMOVNGE,
			MNEMO_CMOVNL,
			MNEMO_CMOVGE,
			MNEMO_CMOVLE,
			MNEMO_CMOVNG,
			MNEMO_CMOVNLE,
			MNEMO_CMOVG,
			MNEMO_MOVMSKPS,
			MNEMO_MOVMSKPD,
			MNEMO_SQRTPS,
			MNEMO_SQRTSS,
			MNEMO_SQRTPD,
			MNEMO_SQRTSD,
			MNEMO_RSQRTPS,
			MNEMO_RSQRTSS,
			MNEMO_RCPPS,
			MNEMO_RCPSS,
			MNEMO_ANDPS,
			MNEMO_ANDPD,
			MNEMO_ANDNPS,
			MNEMO_ANDNPD,
			MNEMO_ORPS,
			MNEMO_ORPD,
			MNEMO_XORPS,
			MNEMO_XORPD,
			MNEMO_ADDPS,
			MNEMO_ADDSS,
			MNEMO_ADDPD,
			MNEMO_ADDSD,
			MNEMO_MULPS,
			MNEMO_MULSS,
			MNEMO_MULPD,
			MNEMO_MULSD,
			MNEMO_CVTPS2PD,
			MNEMO_CVTPD2PS,
			MNEMO_CVTSS2SD,
			MNEMO_CVTSD2SS,
			MNEMO_CVTDQ2PS,
			MNEMO_CVTPS2DQ,
			MNEMO_CVTTPS2DQ,
			MNEMO_SUBPS,
			MNEMO_SUBSS,
			MNEMO_SUBPD,
			MNEMO_SUBSD,
			MNEMO_MINPS,
			MNEMO_MINSS,
			MNEMO_MINPD,
			MNEMO_MINSD,
			MNEMO_DIVPS,
			MNEMO_DIVSS,
			MNEMO_DIVPD,
			MNEMO_DIVSD,
			MNEMO_MAXPS,
			MNEMO_MAXSS,
			MNEMO_MAXPD,
			MNEMO_MAXSD,
			MNEMO_PUNPCKLBW,
			MNEMO_PUNPCKLWD,
			MNEMO_PUNPCKLDQ,
			MNEMO_PACKSSWB,
			MNEMO_PCMPGTB,
			MNEMO_PCMPGTW,
			MNEMO_PCMPGTD,
			MNEMO_PACKUSWB,
			MNEMO_PUNPCKHBW,
			MNEMO_PUNPCKHWD,
			MNEMO_PUNPCKHDQ,
			MNEMO_PACKSSDW,
			MNEMO_PUNPCKLQDQ,
			MNEMO_PUNPCKHQDQ,
			MNEMO_MOVD,
			MNEMO_MOVQ,
			MNEMO_MOVDQA,
			MNEMO_MOVDQU,
			MNEMO_PSHUFW,
			MNEMO_PSHUFLW,
			MNEMO_PSHUFHW,
			MNEMO_PSHUFD,
			MNEMO_PSRLW,
			MNEMO_PSRAW,
			MNEMO_PSLLW,
			MNEMO_PSRLD,
			MNEMO_PSRAD,
			MNEMO_PSLLD,
			MNEMO_PSRLQ,
			MNEMO_PSRLDQ,
			MNEMO_PSLLQ,
			MNEMO_PSLLDQ,
			MNEMO_PCMPEQB,
			MNEMO_PCMPEQW,
			MNEMO_PCMPEQD,
			MNEMO_EMMS,
			MNEMO_VMREAD,
			MNEMO_VMWRITE,
			MNEMO_HADDPD,
			MNEMO_HADDPS,
			MNEMO_HSUBPD,
			MNEMO_HSUBPS,
			MNEMO_SETO,
			MNEMO_SETNO,
			MNEMO_SETB,
			MNEMO_SETNAE,
			MNEMO_SETC,
			MNEMO_SETNB,
			MNEMO_SETAE,
			MNEMO_SETNC,
			MNEMO_SETZ,
			MNEMO_SETE,
			MNEMO_SETNZ,
			MNEMO_SETNE,
			MNEMO_SETBE,
			MNEMO_SETNA,
			MNEMO_SETNBE,
			MNEMO_SETA,
			MNEMO_SETS,
			MNEMO_SETNS,
			MNEMO_SETP,
			MNEMO_SETPE,
			MNEMO_SETNP,
			MNEMO_SETPO,
			MNEMO_SETL,
			MNEMO_SETNGE,
			MNEMO_SETNL,
			MNEMO_SETGE,
			MNEMO_SETLE,
			MNEMO_SETNG,
			MNEMO_SETNLE,
			MNEMO_SETG,
			MNEMO_CPUID,
			MNEMO_BT,
			MNEMO_SHLD,
			MNEMO_RSM,
			MNEMO_BTS,
			MNEMO_SHRD,
			MNEMO_FXSAVE,
			MNEMO_FXRSTOR,
			MNEMO_LDMXCSR,
			MNEMO_STMXCSR,
			MNEMO_XSAVE,
			MNEMO_LFENCE,
			MNEMO_XRSTOR,
			MNEMO_MFENCE,
			MNEMO_SFENCE,
			MNEMO_CLFLUSH,
			MNEMO_CMPXCHG,
			MNEMO_LSS,
			MNEMO_BTR,
			MNEMO_LFS,
			MNEMO_LGS,
			MNEMO_MOVZX,
			MNEMO_POPCNT,
			MNEMO_UD,
			MNEMO_BTC,
			MNEMO_BSF,
			MNEMO_BSR,
			MNEMO_MOVSX,
			MNEMO_XADD,
			MNEMO_CMPPS,
			MNEMO_CMPSS,
			MNEMO_CMPPD,
			MNEMO_MOVNTI,
			MNEMO_PINSRW,
			MNEMO_SHUFPS,
			MNEMO_SHUFPD,
			MNEMO_CMPXCHG8B,
			MNEMO_VMPTRLD,
			MNEMO_VMCLEAR,
			MNEMO_VMXON,
			MNEMO_VMPTRST,
			MNEMO_BSWAP,
			MNEMO_ADDSUBPD,
			MNEMO_ADDSUBPS,
			MNEMO_PADDQ,
			MNEMO_PMULLW,
			MNEMO_MOVQ2DQ,
			MNEMO_MOVDQ2Q,
			MNEMO_PMOVMSKB,
			MNEMO_PSUBUSB,
			MNEMO_PSUBUSW,
			MNEMO_PMINUB,
			MNEMO_PAND,
			MNEMO_PADDUSB,
			MNEMO_PADDUSW,
			MNEMO_PMAXUB,
			MNEMO_PANDN,
			MNEMO_PAVGB,
			MNEMO_PAVGW,
			MNEMO_PMULHUW,
			MNEMO_PMULHW,
			MNEMO_CVTPD2DQ,
			MNEMO_CVTTPD2DQ,
			MNEMO_CVTDQ2PD,
			MNEMO_MOVNTQ,
			MNEMO_MOVNTDQ,
			MNEMO_PSUBSB,
			MNEMO_PSUBSW,
			MNEMO_PMINSW,
			MNEMO_POR,
			MNEMO_PADDSB,
			MNEMO_PADDSW,
			MNEMO_PMAXSW,
			MNEMO_PXOR,
			MNEMO_LDDQU,
			MNEMO_PMULUDQ,
			MNEMO_PMADDWD,
			MNEMO_PSADBW,
			MNEMO_MASKMOVQ,
			MNEMO_MASKMOVDQU,
			MNEMO_PSUBB,
			MNEMO_PSUBW,
			MNEMO_PSUBD,
			MNEMO_PSUBQ,
			MNEMO_PADDB,
			MNEMO_PADDW,
			MNEMO_PADDD,
			MNEMO_NULL
};

//////////////////////////////////
//
//			TABLES
//
//////////////////////////////////

extern const mnemonic_t mnemonics32[];
extern const register_t regs[];
extern const opcodes_t opcodes32[];

//////////////////////////////////
//
//			PREFIX
//
//////////////////////////////////

//////////////////////////////////
//
//			MOD R/M
//
//////////////////////////////////

struct mod_rm_t
{
	uint8_t	rm  : 3;
	uint8_t	reg : 3;
	uint8_t	mod : 2;
};

//////////////////////////////////
//
//			SIB
//
//////////////////////////////////

struct sib_t
{
	uint8_t	base	: 3;
	uint8_t ss 		: 2;
	uint8_t index	: 3;
};

/////////////////////////////////
//
//			INSTRUCTION
//
/////////////////////////////////

struct inst_t
{
};

#endif
